#!/usr/bin/env python3
"""
Local Satellite Pass Predictor — Chagrin Falls, OH
Fetches TLE data from Celestrak and predicts satellite passes using skyfield.
"""

import argparse
import json
import sys
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path

import requests
from skyfield.api import load, wgs84, EarthSatellite
from rich.console import Console
from rich.rule import Rule

# ── Configuration ─────────────────────────────────────────────────────────────

OBSERVER_LAT = 41.4270   # Chagrin Falls, OH
OBSERVER_LON = -81.3990
OBSERVER_ALT = 300       # meters above sea level

DAYS_AHEAD = 3
MIN_ELEVATION = 20       # degrees
TLE_CACHE_DIR = Path(__file__).parent / "tle_cache"
TLE_MAX_AGE_HOURS = 24

RECORD_SCRIPT = "/Users/billfordx/record_noaa.sh"

SATELLITES = [
    {"name": "NOAA 15", "norad": 25338, "freq_mhz": 137.620},
    {"name": "NOAA 18", "norad": 28654, "freq_mhz": 137.9125},
    {"name": "NOAA 19", "norad": 33591, "freq_mhz": 137.100},
    {"name": "ISS",     "norad": 25544, "freq_mhz": 145.800},
]

CELESTRAK_URL = "https://celestrak.org/NORAD/elements/gp.php?CATNR={norad}&FORMAT=TLE"

CRON_START_MARKER = "# AUTO-GENERATED by predict.py — do not edit manually"
CRON_END_MARKER = "# END AUTO-GENERATED"

console = Console()

# ── Azimuth helpers ───────────────────────────────────────────────────────────

def degrees_to_cardinal(deg: float) -> str:
    """Convert an azimuth in degrees to a 16-point compass direction string."""
    dirs = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
            "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"]
    ix = round(deg / 22.5) % 16
    return dirs[ix]


# ── TLE cache ─────────────────────────────────────────────────────────────────

def tle_cache_path(norad: int) -> Path:
    """Return the filesystem path for a cached TLE file by NORAD ID."""
    return TLE_CACHE_DIR / f"{norad}.tle"


def tle_is_fresh(norad: int) -> bool:
    """Return True if the cached TLE for norad exists and is younger than TLE_MAX_AGE_HOURS."""
    path = tle_cache_path(norad)
    if not path.exists():
        return False
    age_hours = (datetime.now().timestamp() - path.stat().st_mtime) / 3600
    return age_hours < TLE_MAX_AGE_HOURS


def fetch_tle(norad: int, force: bool = False) -> tuple[str, str, str]:
    """Return (name, line1, line2), fetching from Celestrak if needed."""
    TLE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = tle_cache_path(norad)

    if not force and tle_is_fresh(norad):
        raw = path.read_text().strip().splitlines()
    else:
        url = CELESTRAK_URL.format(norad=norad)
        try:
            resp = requests.get(url, timeout=10)
            resp.raise_for_status()
        except requests.RequestException as e:
            if path.exists():
                console.print(f"[yellow]TLE fetch failed ({e}), using cached data[/yellow]")
                raw = path.read_text().strip().splitlines()
            else:
                console.print(f"[red]TLE fetch failed and no cache available: {e}[/red]")
                sys.exit(1)
        else:
            text = resp.text.strip()
            path.write_text(text)
            raw = text.splitlines()

    # TLE format: name on line 0, TLE line 1, TLE line 2
    if len(raw) < 3:
        console.print(f"[red]Malformed TLE data for NORAD {norad}[/red]")
        sys.exit(1)

    return raw[0].strip(), raw[1].strip(), raw[2].strip()


# ── Pass prediction ───────────────────────────────────────────────────────────

def predict_passes(sat_cfg: dict, days_ahead: int, min_elevation: float,
                   force_refresh: bool = False) -> list[dict]:
    """Return a list of pass dicts for sat_cfg over the next days_ahead days."""
    # pylint: disable=too-many-locals
    name_cfg = sat_cfg["name"]
    norad    = sat_cfg["norad"]
    freq     = sat_cfg["freq_mhz"]

    tle_name, line1, line2 = fetch_tle(norad, force=force_refresh)

    ts = load.timescale()
    satellite = EarthSatellite(line1, line2, tle_name, ts)
    observer  = wgs84.latlon(OBSERVER_LAT, OBSERVER_LON, elevation_m=OBSERVER_ALT)

    t0 = ts.now()
    t1 = ts.tt_jd(t0.tt + days_ahead)

    times, events = satellite.find_events(observer, t0, t1, altitude_degrees=10.0)

    # Group events into passes: rise(0) → culminate(1) → set(2)
    passes = []
    current = {}

    for t, event in zip(times, events):
        dt = t.utc_datetime()
        diff = satellite - observer
        topo = diff.at(t)
        alt, az, _ = topo.altaz()

        if event == 0:   # AOS
            current = {"aos": dt, "aos_az": az.degrees}
        elif event == 1: # culmination
            current["max_el"] = alt.degrees
        elif event == 2: # LOS
            if "aos" not in current:
                continue
            current["los"] = dt
            current["los_az"] = az.degrees

            if current.get("max_el", 0) < min_elevation:
                current = {}
                continue

            duration = int((current["los"] - current["aos"]).total_seconds())
            passes.append({
                "satellite":        name_cfg,
                "frequency_mhz":    freq,
                "aos":              current["aos"].isoformat(timespec="seconds"),
                "los":              current["los"].isoformat(timespec="seconds"),
                "max_elevation_deg": round(current["max_el"], 1),
                "duration_seconds": duration,
                "aos_azimuth":      degrees_to_cardinal(current["aos_az"]),
                "los_azimuth":      degrees_to_cardinal(current["los_az"]),
            })
            current = {}

    return passes


# ── Output formatters ─────────────────────────────────────────────────────────

def format_duration(seconds: int) -> str:
    """Format a duration in seconds as a human-readable string like '4m 32s'."""
    m, s = divmod(seconds, 60)
    return f"{m}m {s:02d}s"


def print_terminal(  # pylint: disable=too-many-locals
        all_passes: list[dict], min_elevation: float) -> None:
    """Print all passes to the terminal using rich formatting, grouped by satellite."""
    console.print()
    console.print("[bold cyan]Upcoming satellite passes — Chagrin Falls, OH[/bold cyan]")
    console.print(f"[dim]Showing passes with max elevation ≥ {min_elevation:.0f}°[/dim]")
    console.print(Rule(style="dim"))

    # Group by satellite name, preserving order
    seen_names: list[str] = []
    by_sat: dict[str, list[dict]] = {}
    for p in all_passes:
        n = p["satellite"]
        if n not in by_sat:
            by_sat[n] = []
            seen_names.append(n)
        by_sat[n].append(p)

    for name in seen_names:
        passes = by_sat[name]
        freq = passes[0]["frequency_mhz"]
        console.print(f"\n[bold green]{name}[/bold green]  [dim]{freq} MHz[/dim]")

        for p in passes:
            aos_dt = datetime.fromisoformat(p["aos"])
            date_str = aos_dt.strftime("%b %-d")
            time_str = aos_dt.strftime("%H:%M")
            max_el   = p["max_elevation_deg"]
            dur      = format_duration(p["duration_seconds"])
            az_str   = f"{p['aos_azimuth']}→{p['los_azimuth']}"

            el_color = "red" if max_el < 30 else "yellow" if max_el < 60 else "bright_green"
            console.print(
                f"  [cyan]{date_str}[/cyan]  [white]{time_str}[/white]"
                f"  Max: [{el_color}]{max_el:.0f}°[/{el_color}]"
                f"  Duration: [magenta]{dur}[/magenta]"
                f"  [dim]{az_str}[/dim]"
            )

    console.print()


def print_json(all_passes: list[dict]) -> None:
    """Serialize all passes to JSON and print to stdout."""
    output = {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "observer":  {"lat": OBSERVER_LAT, "lon": OBSERVER_LON},
        "passes":    all_passes,
    }
    print(json.dumps(output, indent=2))


# ── Crontab management ────────────────────────────────────────────────────────

def get_crontab() -> str:
    """Return the current crontab contents, or an empty string if none exists."""
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, check=False)
    if result.returncode != 0:
        return ""
    return result.stdout


def set_crontab(content: str) -> None:
    """Write content as the new crontab, exiting on failure."""
    proc = subprocess.run(["crontab", "-"], input=content, text=True,
                          capture_output=True, check=False)
    if proc.returncode != 0:
        console.print(f"[red]Failed to update crontab: {proc.stderr}[/red]")
        sys.exit(1)


def strip_auto_generated(crontab: str) -> str:
    """Remove the AUTO-GENERATED block from crontab text, returning the rest."""
    lines = crontab.splitlines()
    out = []
    inside = False
    for line in lines:
        if line.strip() == CRON_START_MARKER:
            inside = True
        elif line.strip() == CRON_END_MARKER:
            inside = False
        elif not inside:
            out.append(line)
    return "\n".join(out).strip()


def schedule_pass(best_pass: dict) -> None:
    """Write crontab entries to record the given satellite pass."""
    aos = datetime.fromisoformat(best_pass["aos"])
    los = datetime.fromisoformat(best_pass["los"])
    freq = best_pass["frequency_mhz"]
    sat  = best_pass["satellite"]

    # Schedule record to start 1 minute before AOS
    start = aos - timedelta(minutes=1)
    stop  = los + timedelta(seconds=30)

    start_cron = f"{start.minute} {start.hour} {start.day} {start.month} *"
    stop_cron  = f"{stop.minute} {stop.hour} {stop.day} {stop.month} *"

    record_line = f"{start_cron} {RECORD_SCRIPT} {freq}M"
    stop_line   = f"{stop_cron} pkill -f rtl_fm"

    existing = get_crontab()
    cleaned  = strip_auto_generated(existing)

    new_block = "\n".join([
        CRON_START_MARKER,
        record_line,
        stop_line,
        CRON_END_MARKER,
    ])

    final = (cleaned.rstrip() + "\n" + new_block + "\n") if cleaned.strip() else (new_block + "\n")
    set_crontab(final)

    console.print(f"\n[bold green]Crontab updated for {sat} pass[/bold green]")
    console.print(f"  Start: [cyan]{aos.strftime('%Y-%m-%d %H:%M')} UTC[/cyan]  ({start_cron})")
    console.print(f"  Stop:  [cyan]{los.strftime('%Y-%m-%d %H:%M')} UTC[/cyan]  ({stop_cron})")
    console.print(f"  Freq:  [yellow]{freq} MHz[/yellow]")
    console.print(
        f"  Max elevation: [bright_green]{best_pass['max_elevation_deg']:.0f}°"
        "[/bright_green]\n"
    )


# ── CLI ───────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    """Build and return the CLI argument parser."""
    p = argparse.ArgumentParser(
        description="Predict satellite passes over Chagrin Falls, OH"
    )
    p.add_argument("--days",          type=int,   default=DAYS_AHEAD,
                   help=f"Days ahead to predict (default: {DAYS_AHEAD})")
    p.add_argument("--min-elevation", type=float, default=MIN_ELEVATION,
                   help=f"Minimum max elevation in degrees (default: {MIN_ELEVATION})")
    p.add_argument("--json",          action="store_true",
                   help="Output JSON instead of rich terminal table")
    p.add_argument("--schedule",      action="store_true",
                   help="Update crontab for next best pass")
    p.add_argument("--satellite",     type=str,   default=None,
                   help='Filter to a single satellite by name, e.g. "NOAA 19"')
    p.add_argument("--refresh",       action="store_true",
                   help="Force TLE refresh from Celestrak")
    return p


def main() -> None:
    """Entry point: parse args, predict passes, and display or schedule them."""
    args = build_parser().parse_args()

    sats = SATELLITES
    if args.satellite:
        sats = [s for s in SATELLITES if s["name"].lower() == args.satellite.lower()]
        if not sats:
            names = ", ".join(s["name"] for s in SATELLITES)
            console.print(f"[red]Unknown satellite '{args.satellite}'. Choose from: {names}[/red]")
            sys.exit(1)

    all_passes: list[dict] = []
    for sat in sats:
        passes = predict_passes(sat, args.days, args.min_elevation, force_refresh=args.refresh)
        all_passes.extend(passes)

    # Sort chronologically
    all_passes.sort(key=lambda p: p["aos"])

    if args.json:
        print_json(all_passes)
        return

    print_terminal(all_passes, args.min_elevation)

    if args.schedule:
        if not all_passes:
            console.print(
                "[yellow]No passes found meeting the elevation threshold"
                " — crontab not updated.[/yellow]"
            )
            return
        # Pick the pass with the highest max elevation as the "best"
        best = max(all_passes, key=lambda p: p["max_elevation_deg"])
        schedule_pass(best)


if __name__ == "__main__":
    main()
